services:
  web-api:
    image: ${DOCKER_REGISTRY-}webapi
    container_name: web-api
    build:
      context: .
      dockerfile: src/Loop.Web.Api/Dockerfile
    ports:
      - 5000:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__Database=Host=db.laxobptskpcksdrnvaxp.supabase.co;Port=5432;Database=postgres;Username=postgres;Password=LoopSoftware200;SSL Mode=Require;Trust Server Certificate=true

  seq:
    image: datalust/seq:2024.3
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 8081:80