// <auto-generated />
using System;
using Loop.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Loop.Infrastructure.Migrations;

[DbContext(typeof(LoopContext))]
[Migration("20260609123956_AddShopAdminRole")]
partial class AddShopAdminRole
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("public")
            .HasAnnotation("ProductVersion", "10.0.5")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Loop.Domain.Audit.AuditLog", b =>
        {
            b.Property<Guid>("LogId")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("log_id");

            b.Property<string>("ActionType")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("character varying(100)")
                .HasColumnName("action_type");

            b.Property<string>("AdminType")
                .HasMaxLength(20)
                .HasColumnType("character varying(20)")
                .HasColumnName("admin_type");

            b.Property<DateTime>("CreatedAt")
                .ValueGeneratedOnAdd()
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at")
                .HasDefaultValueSql("now()");

            b.Property<Guid?>("MallAdminId")
                .HasColumnType("uuid")
                .HasColumnName("mall_admin_id");

            b.Property<string>("Metadata")
                .HasColumnType("jsonb")
                .HasColumnName("metadata");

            b.Property<int?>("Points")
                .HasColumnType("integer")
                .HasColumnName("points");

            b.Property<Guid?>("ShopAdminId")
                .HasColumnType("uuid")
                .HasColumnName("shop_admin_id");

            b.Property<Guid?>("ShopId")
                .HasColumnType("uuid")
                .HasColumnName("shop_id");

            b.Property<Guid?>("UserId")
                .HasColumnType("uuid")
                .HasColumnName("user_id");

            b.HasKey("LogId")
                .HasName("pk_audit_log");

            b.HasIndex("CreatedAt")
                .HasDatabaseName("ix_audit_log_created_at");

            b.HasIndex("MallAdminId")
                .HasDatabaseName("ix_audit_log_mall_admin_id");

            b.HasIndex("ShopAdminId")
                .HasDatabaseName("ix_audit_log_shop_admin_id");

            b.HasIndex("ShopId")
                .HasDatabaseName("ix_audit_log_shop_id");

            b.HasIndex("UserId")
                .HasDatabaseName("ix_audit_log_user_id");

            b.ToTable("audit_log", "public");
        });

        modelBuilder.Entity("Loop.Domain.Configuration.SystemConfig", b =>
        {
            b.Property<Guid>("ConfigId")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("config_id");

            b.Property<decimal>("EarnPointsPerCurrency")
                .HasPrecision(10, 2)
                .HasColumnType("numeric(10,2)")
                .HasColumnName("earn_points_per_currency");

            b.Property<Guid>("MallId")
                .HasColumnType("uuid")
                .HasColumnName("mall_id");

            b.Property<int>("MinRedemptionThreshold")
                .HasColumnType("integer")
                .HasColumnName("min_redemption_threshold");

            b.Property<decimal>("PointsToCurrencyRatio")
                .HasPrecision(10, 4)
                .HasColumnType("numeric(10,4)")
                .HasColumnName("points_to_currency_ratio");

            b.Property<DateTime>("UpdatedAt")
                .ValueGeneratedOnAdd()
                .HasColumnType("timestamp with time zone")
                .HasColumnName("updated_at")
                .HasDefaultValueSql("now()");

            b.Property<Guid>("UpdatedByAdminId")
                .HasColumnType("uuid")
                .HasColumnName("updated_by_admin_id");

            b.HasKey("ConfigId")
                .HasName("pk_system_config");

            b.HasIndex("MallId")
                .IsUnique()
                .HasDatabaseName("ix_system_config_mall_id");

            b.HasIndex("UpdatedByAdminId")
                .HasDatabaseName("ix_system_config_updated_by_admin_id");

            b.ToTable("system_config", "public");

            b.HasData(
                new
                {
                    ConfigId = new Guid("66666666-6666-6666-6666-666666666666"),
                    EarnPointsPerCurrency = 1.00m,
                    MallId = new Guid("d86d8ee3-4bf9-47a8-b2c2-81a6f09bf001"),
                    MinRedemptionThreshold = 100,
                    PointsToCurrencyRatio = 0.0100m,
                    UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                    UpdatedByAdminId = new Guid("55555555-5555-5555-5555-555555555555")
                });
        });

        modelBuilder.Entity("Loop.Domain.Malls.Mall", b =>
        {
            b.Property<Guid>("MallId")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("mall_id");

            b.Property<string>("CoverImageUrl")
                .HasMaxLength(512)
                .HasColumnType("character varying(512)")
                .HasColumnName("cover_image_url");

            b.Property<DateTime>("CreatedAt")
                .ValueGeneratedOnAdd()
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at")
                .HasDefaultValueSql("now()");

            b.Property<string>("Location")
                .HasMaxLength(500)
                .HasColumnType("character varying(500)")
                .HasColumnName("location");

            b.Property<string>("LogoUrl")
                .HasMaxLength(512)
                .HasColumnType("character varying(512)")
                .HasColumnName("logo_url");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("character varying(200)")
                .HasColumnName("name");

            b.HasKey("MallId")
                .HasName("pk_mall");

            b.HasIndex("Name")
                .IsUnique()
                .HasDatabaseName("ix_mall_name");

            b.ToTable("mall", "public");

            b.HasData(
                new
                {
                    MallId = new Guid("d86d8ee3-4bf9-47a8-b2c2-81a6f09bf001"),
                    CoverImageUrl = "https://cdn.loop.local/malls/loop-central-cover.png",
                    CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                    Location = "Amman, Jordan",
                    LogoUrl = "https://cdn.loop.local/malls/loop-central-logo.png",
                    Name = "Loop Central Mall"
                });
        });

        modelBuilder.Entity("Loop.Domain.Malls.MallAdmin", b =>
        {
            b.Property<Guid>("MallAdminId")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("mall_admin_id");

            b.Property<DateTime>("CreatedAt")
                .ValueGeneratedOnAdd()
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at")
                .HasDefaultValueSql("now()");

            b.Property<string>("Email")
                .IsRequired()
                .HasMaxLength(256)
                .HasColumnType("character varying(256)")
                .HasColumnName("email");

            b.Property<Guid>("MallId")
                .HasColumnType("uuid")
                .HasColumnName("mall_id");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("character varying(200)")
                .HasColumnName("name");

            b.Property<string>("PasswordHash")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("password_hash");

            b.Property<string>("Phone")
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnType("character varying(20)")
                .HasColumnName("phone");

            b.HasKey("MallAdminId")
                .HasName("pk_mall_admin");

            b.HasIndex("Email")
                .IsUnique()
                .HasDatabaseName("ix_mall_admin_email");

            b.HasIndex("MallId")
                .HasDatabaseName("ix_mall_admin_mall_id");

            b.HasIndex("Phone")
                .IsUnique()
                .HasDatabaseName("ix_mall_admin_phone");

            b.ToTable("mall_admin", "public");

            b.HasData(
                new
                {
                    MallAdminId = new Guid("55555555-5555-5555-5555-555555555555"),
                    CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                    Email = "MALL.ADMIN@LOOP.LOCAL",
                    MallId = new Guid("d86d8ee3-4bf9-47a8-b2c2-81a6f09bf001"),
                    Name = "Loop Mall Admin",
                    PasswordHash = "seeded-password-hash",
                    Phone = "+962790000003"
                });
        });

        modelBuilder.Entity("Loop.Domain.Malls.MallAdminPasswordResetRequest", b =>
        {
            b.Property<Guid>("RequestId")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("request_id");

            b.Property<DateTime>("ExpiresAtUtc")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("expires_at_utc");

            b.Property<Guid>("MallAdminId")
                .HasColumnType("uuid")
                .HasColumnName("mall_admin_id");

            b.Property<string>("TokenHash")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("character varying(128)")
                .HasColumnName("token_hash");

            b.HasKey("RequestId")
                .HasName("pk_mall_admin_password_reset_request");

            b.HasIndex("MallAdminId")
                .IsUnique()
                .HasDatabaseName("ix_mall_admin_password_reset_request_mall_admin_id");

            b.HasIndex("TokenHash")
                .IsUnique()
                .HasDatabaseName("ix_mall_admin_password_reset_request_token_hash");

            b.ToTable("mall_admin_password_reset_request", "public");
        });

        modelBuilder.Entity("Loop.Domain.Malls.MallAdminSession", b =>
        {
            b.Property<Guid>("SessionId")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("session_id");

            b.Property<DateTime>("CreatedAt")
                .ValueGeneratedOnAdd()
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at")
                .HasDefaultValueSql("now()");

            b.Property<DateTime>("ExpiresAtUtc")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("expires_at_utc");

            b.Property<Guid>("MallAdminId")
                .HasColumnType("uuid")
                .HasColumnName("mall_admin_id");

            b.Property<string>("RefreshTokenHash")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("character varying(128)")
                .HasColumnName("refresh_token_hash");

            b.HasKey("SessionId")
                .HasName("pk_mall_admin_session");

            b.HasIndex("MallAdminId")
                .HasDatabaseName("ix_mall_admin_session_mall_admin_id");

            b.HasIndex("RefreshTokenHash")
                .IsUnique()
                .HasDatabaseName("ix_mall_admin_session_refresh_token_hash");

            b.ToTable("mall_admin_session", "public");
        });

        modelBuilder.Entity("Loop.Domain.Offers.Offer", b =>
        {
            b.Property<Guid>("OfferId")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("offer_id");

            b.Property<DateTime>("CreatedAt")
                .ValueGeneratedOnAdd()
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at")
                .HasDefaultValueSql("now()");

            b.Property<string>("Description")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("description");

            b.Property<DateTime>("EndDate")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("end_date");

            b.Property<string>("ImageUrl")
                .IsRequired()
                .HasMaxLength(512)
                .HasColumnType("character varying(512)")
                .HasColumnName("image_url");

            b.Property<bool>("IsActive")
                .ValueGeneratedOnAdd()
                .HasColumnType("boolean")
                .HasDefaultValue(true)
                .HasColumnName("is_active");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("character varying(200)")
                .HasColumnName("name");

            b.Property<string>("RewardType")
                .IsRequired()
                .HasMaxLength(30)
                .HasColumnType("character varying(30)")
                .HasColumnName("reward_type");

            b.Property<string>("RewardValue")
                .IsRequired()
                .HasColumnType("jsonb")
                .HasColumnName("reward_value");

            b.Property<Guid>("ShopId")
                .HasColumnType("uuid")
                .HasColumnName("shop_id");

            b.Property<DateTime>("StartDate")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("start_date");

            b.HasKey("OfferId")
                .HasName("pk_offer");

            b.HasIndex("IsActive")
                .HasDatabaseName("ix_offer_is_active");

            b.HasIndex("ShopId")
                .HasDatabaseName("ix_offer_shop_id");

            b.HasIndex("StartDate")
                .HasDatabaseName("ix_offer_start_date");

            b.ToTable("offer", "public");

            b.HasData(
                new
                {
                    OfferId = new Guid("77777777-7777-7777-7777-777777777777"),
                    CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                    Description = "Get 10% discount on any drink.",
                    EndDate = new DateTime(2027, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                    ImageUrl = "https://cdn.loop.local/offers/ten-percent.png",
                    IsActive = true,
                    Name = "10% Off Drinks",
                    RewardType = "Discount",
                    RewardValue = "{\"percent\":10}",
                    ShopId = new Guid("7d5dc255-7f80-4f6f-b962-b83f0d0ac001"),
                    StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                },
                new
                {
                    OfferId = new Guid("77777777-7777-7777-7777-777777777778"),
                    CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                    Description = "Buy 2 items and get 1 free.",
                    EndDate = new DateTime(2027, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                    ImageUrl = "https://cdn.loop.local/offers/buy2get1.png",
                    IsActive = true,
                    Name = "Buy 2 Get 1",
                    RewardType = "Discount",
                    RewardValue = "{\"type\":\"buy2get1\"}",
                    ShopId = new Guid("7d5dc255-7f80-4f6f-b962-b83f0d0ac002"),
                    StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                },
                new
                {
                    OfferId = new Guid("77777777-7777-7777-7777-777777777779"),
                    CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                    Description = "Get a free accessory with selected devices.",
                    EndDate = new DateTime(2027, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                    ImageUrl = "https://cdn.loop.local/offers/free-accessory.png",
                    IsActive = true,
                    Name = "Free Accessory",
                    RewardType = "Discount",
                    RewardValue = "{\"value\":\"free_accessory\"}",
                    ShopId = new Guid("7d5dc255-7f80-4f6f-b962-b83f0d0ac003"),
                    StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                });
        });

        modelBuilder.Entity("Loop.Domain.Offers.OfferRedemption", b =>
        {
            b.Property<Guid>("RedemptionId")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("redemption_id");

            b.Property<DateTime?>("ConfirmedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("confirmed_at");

            b.Property<DateTime>("CreatedAt")
                .ValueGeneratedOnAdd()
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at")
                .HasDefaultValueSql("now()");

            b.Property<Guid>("OfferId")
                .HasColumnType("uuid")
                .HasColumnName("offer_id");

            b.Property<Guid?>("QrId")
                .HasColumnType("uuid")
                .HasColumnName("qr_id");

            b.Property<Guid>("ShopId")
                .HasColumnType("uuid")
                .HasColumnName("shop_id");

            b.Property<int>("Status")
                .ValueGeneratedOnAdd()
                .HasColumnType("integer")
                .HasDefaultValue(1)
                .HasColumnName("status");

            b.Property<Guid>("UserId")
                .HasColumnType("uuid")
                .HasColumnName("user_id");

            b.HasKey("RedemptionId")
                .HasName("pk_offer_redemption");

            b.HasIndex("OfferId")
                .HasDatabaseName("ix_offer_redemption_offer_id");

            b.HasIndex("ShopId")
                .HasDatabaseName("ix_offer_redemption_shop_id");

            b.HasIndex("Status")
                .HasDatabaseName("ix_offer_redemption_status");

            b.HasIndex("UserId")
                .HasDatabaseName("ix_offer_redemption_user_id");

            b.HasIndex("UserId", "OfferId")
                .HasDatabaseName("ix_offer_redemption_user_id_offer_id");

            b.ToTable("offer_redemption", "public");
        });

        modelBuilder.Entity("Loop.Domain.QRCode.QrCode", b =>
        {
            b.Property<Guid>("QrId")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("qr_id");

            b.Property<DateTime>("ExpiresAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("expires_at");

            b.Property<string>("QrCodeData")
                .IsRequired()
                .HasColumnType("jsonb")
                .HasColumnName("qr_code_data");

            b.Property<Guid?>("ShopId")
                .HasColumnType("uuid")
                .HasColumnName("shop_id");

            b.Property<Guid?>("UserId")
                .HasColumnType("uuid")
                .HasColumnName("user_id");

            b.HasKey("QrId")
                .HasName("pk_qr_code");

            b.HasIndex("ExpiresAt")
                .HasDatabaseName("ix_qr_code_expires_at");

            b.HasIndex("ShopId")
                .HasDatabaseName("ix_qr_code_shop_id");

            b.HasIndex("UserId")
                .HasDatabaseName("ix_qr_code_user_id");

            b.ToTable("qr_code", "public");
        });

        modelBuilder.Entity("Loop.Domain.Receipts.Receipt", b =>
        {
            b.Property<Guid>("ReceiptId")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("receipt_id");

            b.Property<DateTime>("CreatedAt")
                .ValueGeneratedOnAdd()
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at")
                .HasDefaultValueSql("now()");

            b.Property<string>("ImageHash")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("character varying(64)")
                .HasColumnName("image_hash");

            b.Property<string>("ReceiptDetails")
                .IsRequired()
                .HasColumnType("jsonb")
                .HasColumnName("receipt_details");

            b.Property<string>("ReceiptPath")
                .IsRequired()
                .HasMaxLength(512)
                .HasColumnType("character varying(512)")
                .HasColumnName("receipt_path");

            b.Property<Guid>("ShopId")
                .HasColumnType("uuid")
                .HasColumnName("shop_id");

            b.Property<string>("Status")
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnType("character varying(20)")
                .HasColumnName("status");

            b.Property<Guid>("UserId")
                .HasColumnType("uuid")
                .HasColumnName("user_id");

            b.HasKey("ReceiptId")
                .HasName("pk_receipt");

            b.HasIndex("ImageHash")
                .IsUnique()
                .HasDatabaseName("ix_receipt_image_hash");

            b.HasIndex("ShopId")
                .HasDatabaseName("ix_receipt_shop_id");

            b.HasIndex("Status")
                .HasDatabaseName("ix_receipt_status");

            b.HasIndex("UserId")
                .HasDatabaseName("ix_receipt_user_id");

            b.ToTable("receipt", "public");

            b.HasData(
                new
                {
                    ReceiptId = new Guid("88888888-8888-8888-8888-888888888888"),
                    CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                    ImageHash = "0000000000000000000000000000000000000000000000000000000000000000",
                    ReceiptDetails = "{\"items\":1,\"source\":\"seed\"}",
                    ReceiptPath = "receipts/2026/seed-receipt-1.jpg",
                    ShopId = new Guid("7d5dc255-7f80-4f6f-b962-b83f0d0ac001"),
                    Status = "Approved",
                    UserId = new Guid("22222222-2222-2222-2222-222222222222")
                });
        });

        modelBuilder.Entity("Loop.Domain.Shops.Category", b =>
        {
            b.Property<Guid>("CategoryId")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("category_id");

            b.Property<DateTime>("CreatedAt")
                .ValueGeneratedOnAdd()
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at")
                .HasDefaultValueSql("now()");

            b.Property<string>("Description")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("description");

            b.Property<int>("DisplayOrder")
                .ValueGeneratedOnAdd()
                .HasColumnType("integer")
                .HasDefaultValue(0)
                .HasColumnName("display_order");

            b.Property<string>("IconUrl")
                .IsRequired()
                .HasMaxLength(512)
                .HasColumnType("character varying(512)")
                .HasColumnName("icon_url");

            b.Property<Guid>("MallId")
                .HasColumnType("uuid")
                .HasColumnName("mall_id");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("character varying(200)")
                .HasColumnName("name");

            b.HasKey("CategoryId")
                .HasName("pk_category");

            b.HasIndex("MallId")
                .HasDatabaseName("ix_category_mall_id");

            b.HasIndex("Name")
                .IsUnique()
                .HasDatabaseName("ix_category_name");

            b.ToTable("category", "public");

            b.HasData(
                new
                {
                    CategoryId = new Guid("9f6454d5-a767-4c2f-a38d-cf6c9ee1ec01"),
                    CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                    Description = "Coffee and beverages",
                    DisplayOrder = 1,
                    IconUrl = "https://cdn.loop.local/icons/coffee.png",
                    MallId = new Guid("d86d8ee3-4bf9-47a8-b2c2-81a6f09bf001"),
                    Name = "Coffee"
                },
                new
                {
                    CategoryId = new Guid("9f6454d5-a767-4c2f-a38d-cf6c9ee1ec02"),
                    CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                    Description = "Clothing, shoes and accessories",
                    DisplayOrder = 2,
                    IconUrl = "https://cdn.loop.local/icons/fashion.png",
                    MallId = new Guid("d86d8ee3-4bf9-47a8-b2c2-81a6f09bf001"),
                    Name = "Fashion"
                },
                new
                {
                    CategoryId = new Guid("9f6454d5-a767-4c2f-a38d-cf6c9ee1ec03"),
                    CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                    Description = "Phones, gadgets and accessories",
                    DisplayOrder = 3,
                    IconUrl = "https://cdn.loop.local/icons/electronics.png",
                    MallId = new Guid("d86d8ee3-4bf9-47a8-b2c2-81a6f09bf001"),
                    Name = "Electronics"
                });
        });

        modelBuilder.Entity("Loop.Domain.Shops.Shop", b =>
        {
            b.Property<Guid>("ShopId")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("shop_id");

            b.Property<string>("Bio")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("bio");

            b.Property<Guid>("CategoryId")
                .HasColumnType("uuid")
                .HasColumnName("category_id");

            b.Property<string>("CoverImageUrl")
                .IsRequired()
                .HasMaxLength(512)
                .HasColumnType("character varying(512)")
                .HasColumnName("cover_image_url");

            b.Property<DateTime>("CreatedAt")
                .ValueGeneratedOnAdd()
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at")
                .HasDefaultValueSql("now()");

            b.Property<bool>("IsActive")
                .ValueGeneratedOnAdd()
                .HasColumnType("boolean")
                .HasDefaultValue(true)
                .HasColumnName("is_active");

            b.Property<string>("LogoUrl")
                .IsRequired()
                .HasMaxLength(512)
                .HasColumnType("character varying(512)")
                .HasColumnName("logo_url");

            b.Property<Guid>("MallId")
                .HasColumnType("uuid")
                .HasColumnName("mall_id");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("character varying(200)")
                .HasColumnName("name");

            b.Property<string>("SocialLinks")
                .HasColumnType("jsonb")
                .HasColumnName("social_links");

            b.Property<string>("WebsiteUrl")
                .HasMaxLength(512)
                .HasColumnType("character varying(512)")
                .HasColumnName("website_url");

            b.HasKey("ShopId")
                .HasName("pk_shop");

            b.HasIndex("CategoryId")
                .HasDatabaseName("ix_shop_category_id");

            b.HasIndex("MallId")
                .HasDatabaseName("ix_shop_mall_id");

            b.HasIndex("Name")
                .IsUnique()
                .HasDatabaseName("ix_shop_name");

            b.ToTable("shop", "public");

            b.HasData(
                new
                {
                    ShopId = new Guid("7d5dc255-7f80-4f6f-b962-b83f0d0ac001"),
                    Bio = "Specialty coffee and pastries.",
                    CategoryId = new Guid("9f6454d5-a767-4c2f-a38d-cf6c9ee1ec01"),
                    CoverImageUrl = "https://cdn.loop.local/shops/loop-coffee-cover.png",
                    CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                    IsActive = true,
                    LogoUrl = "https://cdn.loop.local/shops/loop-coffee-logo.png",
                    MallId = new Guid("d86d8ee3-4bf9-47a8-b2c2-81a6f09bf001"),
                    Name = "Loop Coffee",
                    SocialLinks = "{\"instagram\":\"@loopcoffee\"}",
                    WebsiteUrl = "https://loop-coffee.local"
                },
                new
                {
                    ShopId = new Guid("7d5dc255-7f80-4f6f-b962-b83f0d0ac002"),
                    Bio = "Streetwear and seasonal fashion.",
                    CategoryId = new Guid("9f6454d5-a767-4c2f-a38d-cf6c9ee1ec02"),
                    CoverImageUrl = "https://cdn.loop.local/shops/urban-wear-cover.png",
                    CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                    IsActive = true,
                    LogoUrl = "https://cdn.loop.local/shops/urban-wear-logo.png",
                    MallId = new Guid("d86d8ee3-4bf9-47a8-b2c2-81a6f09bf001"),
                    Name = "Urban Wear",
                    SocialLinks = "{\"instagram\":\"@urbanwear\"}",
                    WebsiteUrl = "https://urban-wear.local"
                },
                new
                {
                    ShopId = new Guid("7d5dc255-7f80-4f6f-b962-b83f0d0ac003"),
                    Bio = "Latest smartphones, audio and gadgets.",
                    CategoryId = new Guid("9f6454d5-a767-4c2f-a38d-cf6c9ee1ec03"),
                    CoverImageUrl = "https://cdn.loop.local/shops/tech-zone-cover.png",
                    CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                    IsActive = true,
                    LogoUrl = "https://cdn.loop.local/shops/tech-zone-logo.png",
                    MallId = new Guid("d86d8ee3-4bf9-47a8-b2c2-81a6f09bf001"),
                    Name = "Tech Zone",
                    SocialLinks = "{\"instagram\":\"@techzone\"}",
                    WebsiteUrl = "https://tech-zone.local"
                });
        });

        modelBuilder.Entity("Loop.Domain.Shops.ShopAdmin", b =>
        {
            b.Property<Guid>("ShopAdminId")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("shop_admin_id");

            b.Property<DateTime>("CreatedAt")
                .ValueGeneratedOnAdd()
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at")
                .HasDefaultValueSql("now()");

            b.Property<bool>("IsActive")
                .ValueGeneratedOnAdd()
                .HasColumnType("boolean")
                .HasDefaultValue(true)
                .HasColumnName("is_active");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("character varying(200)")
                .HasColumnName("name");

            b.Property<string>("PasswordHash")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("password_hash");

            b.Property<string>("Phone")
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnType("character varying(20)")
                .HasColumnName("phone");

            b.Property<string>("Role")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("role");

            b.Property<Guid>("ShopId")
                .HasColumnType("uuid")
                .HasColumnName("shop_id");

            b.HasKey("ShopAdminId")
                .HasName("pk_shop_admin");

            b.HasIndex("Phone")
                .IsUnique()
                .HasDatabaseName("ix_shop_admin_phone");

            b.HasIndex("ShopId")
                .HasDatabaseName("ix_shop_admin_shop_id");

            b.ToTable("shop_admin", "public");
        });

        modelBuilder.Entity("Loop.Domain.Shops.ShopAdminPasswordResetRequest", b =>
        {
            b.Property<Guid>("RequestId")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("request_id");

            b.Property<DateTime>("ExpiresAtUtc")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("expires_at_utc");

            b.Property<Guid>("ShopAdminId")
                .HasColumnType("uuid")
                .HasColumnName("shop_admin_id");

            b.Property<string>("TokenHash")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("character varying(128)")
                .HasColumnName("token_hash");

            b.HasKey("RequestId")
                .HasName("pk_shop_admin_password_reset_request");

            b.HasIndex("ShopAdminId")
                .IsUnique()
                .HasDatabaseName("ix_shop_admin_password_reset_request_shop_admin_id");

            b.HasIndex("TokenHash")
                .IsUnique()
                .HasDatabaseName("ix_shop_admin_password_reset_request_token_hash");

            b.ToTable("shop_admin_password_reset_request", "public");
        });

        modelBuilder.Entity("Loop.Domain.Shops.ShopAdminSession", b =>
        {
            b.Property<Guid>("SessionId")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("session_id");

            b.Property<DateTime>("CreatedAt")
                .ValueGeneratedOnAdd()
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at")
                .HasDefaultValueSql("now()");

            b.Property<DateTime>("ExpiresAtUtc")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("expires_at_utc");

            b.Property<string>("RefreshTokenHash")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("character varying(128)")
                .HasColumnName("refresh_token_hash");

            b.Property<Guid>("ShopAdminId")
                .HasColumnType("uuid")
                .HasColumnName("shop_admin_id");

            b.HasKey("SessionId")
                .HasName("pk_mall_admin_session");

            b.HasIndex("RefreshTokenHash")
                .IsUnique()
                .HasDatabaseName("ix_mall_admin_session_refresh_token_hash");

            b.HasIndex("ShopAdminId")
                .HasDatabaseName("ix_mall_admin_session_shop_admin_id");

            b.ToTable("mall_admin_session", "public");
        });

        modelBuilder.Entity("Loop.Domain.Shops.ShopPointsWallet", b =>
        {
            b.Property<Guid>("ShopId")
                .HasColumnType("uuid")
                .HasColumnName("shop_id");

            b.Property<DateTime>("LastUpdated")
                .ValueGeneratedOnAdd()
                .HasColumnType("timestamp with time zone")
                .HasColumnName("last_updated")
                .HasDefaultValueSql("now()");

            b.Property<int>("PointsReceived")
                .ValueGeneratedOnAdd()
                .HasColumnType("integer")
                .HasDefaultValue(0)
                .HasColumnName("points_received");

            b.HasKey("ShopId")
                .HasName("pk_shop_points_wallet");

            b.ToTable("shop_points_wallet", "public");
        });

        modelBuilder.Entity("Loop.Domain.Stamps.Stamp", b =>
        {
            b.Property<Guid>("StampId")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("stamp_id");

            b.Property<DateTime>("CreatedAt")
                .ValueGeneratedOnAdd()
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at")
                .HasDefaultValueSql("now()");

            b.Property<string>("Description")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("description");

            b.Property<DateTime>("EndDate")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("end_date");

            b.Property<string>("ImageUrl")
                .IsRequired()
                .HasMaxLength(512)
                .HasColumnType("character varying(512)")
                .HasColumnName("image_url");

            b.Property<bool>("IsActive")
                .ValueGeneratedOnAdd()
                .HasColumnType("boolean")
                .HasDefaultValue(true)
                .HasColumnName("is_active");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("character varying(200)")
                .HasColumnName("name");

            b.Property<string>("RewardType")
                .IsRequired()
                .HasMaxLength(30)
                .HasColumnType("character varying(30)")
                .HasColumnName("reward_type");

            b.Property<Guid>("ShopId")
                .HasColumnType("uuid")
                .HasColumnName("shop_id");

            b.Property<string>("StampIconUrl")
                .IsRequired()
                .HasMaxLength(512)
                .HasColumnType("character varying(512)")
                .HasColumnName("stamp_icon_url");

            b.Property<int>("StampsRequired")
                .HasColumnType("integer")
                .HasColumnName("stamps_required");

            b.Property<DateTime>("StartDate")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("start_date");

            b.HasKey("StampId")
                .HasName("pk_stamp");

            b.HasIndex("IsActive")
                .HasDatabaseName("ix_stamp_is_active");

            b.HasIndex("ShopId")
                .HasDatabaseName("ix_stamp_shop_id");

            b.ToTable("stamp", "public");

            b.HasData(
                new
                {
                    StampId = new Guid("3f3f3f15-0d2e-4ef6-8e55-8ebf30c81001"),
                    CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                    Description = "Collect 9 stamps and get your next drink free.",
                    EndDate = new DateTime(2027, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                    ImageUrl = "https://cdn.loop.local/stamps/loop-coffee-card.png",
                    IsActive = true,
                    Name = "Buy 9 Get 1 Free",
                    RewardType = "Reward",
                    ShopId = new Guid("7d5dc255-7f80-4f6f-b962-b83f0d0ac001"),
                    StampIconUrl = "https://cdn.loop.local/stamps/loop-coffee-icon.png",
                    StampsRequired = 10,
                    StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                });
        });

        modelBuilder.Entity("Loop.Domain.Stamps.StampRedemption", b =>
        {
            b.Property<Guid>("RedemptionId")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("redemption_id");

            b.Property<DateTime>("CreatedAt")
                .ValueGeneratedOnAdd()
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at")
                .HasDefaultValueSql("now()");

            b.Property<Guid>("QrId")
                .HasColumnType("uuid")
                .HasColumnName("qr_id");

            b.Property<Guid>("ShopId")
                .HasColumnType("uuid")
                .HasColumnName("shop_id");

            b.Property<Guid>("StampId")
                .HasColumnType("uuid")
                .HasColumnName("stamp_id");

            b.Property<Guid>("UserId")
                .HasColumnType("uuid")
                .HasColumnName("user_id");

            b.HasKey("RedemptionId")
                .HasName("pk_stamp_redemption");

            b.HasIndex("QrId")
                .IsUnique()
                .HasDatabaseName("ix_stamp_redemption_qr_id");

            b.HasIndex("ShopId")
                .HasDatabaseName("ix_stamp_redemption_shop_id");

            b.HasIndex("StampId")
                .HasDatabaseName("ix_stamp_redemption_stamp_id");

            b.HasIndex("UserId")
                .HasDatabaseName("ix_stamp_redemption_user_id");

            b.HasIndex("UserId", "StampId")
                .HasDatabaseName("ix_stamp_redemption_user_id_stamp_id");

            b.ToTable("stamp_redemption", "public");
        });

        modelBuilder.Entity("Loop.Domain.Stamps.StampTransaction", b =>
        {
            b.Property<Guid>("StampTxId")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("stamp_tx_id");

            b.Property<DateTime>("CreatedAt")
                .ValueGeneratedOnAdd()
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at")
                .HasDefaultValueSql("now()");

            b.Property<Guid?>("RedemptionRef")
                .HasColumnType("uuid")
                .HasColumnName("redemption_ref");

            b.Property<Guid>("ShopId")
                .HasColumnType("uuid")
                .HasColumnName("shop_id");

            b.Property<Guid>("StampProgramId")
                .HasColumnType("uuid")
                .HasColumnName("stamp_program_id");

            b.Property<int>("StampsCount")
                .HasColumnType("integer")
                .HasColumnName("stamps_count");

            b.Property<string>("Type")
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnType("character varying(20)")
                .HasColumnName("type");

            b.Property<Guid>("UserId")
                .HasColumnType("uuid")
                .HasColumnName("user_id");

            b.HasKey("StampTxId")
                .HasName("pk_stamp_transaction");

            b.HasIndex("RedemptionRef")
                .HasDatabaseName("ix_stamp_transaction_redemption_ref");

            b.HasIndex("ShopId")
                .HasDatabaseName("ix_stamp_transaction_shop_id");

            b.HasIndex("StampProgramId")
                .HasDatabaseName("ix_stamp_transaction_stamp_program_id");

            b.HasIndex("UserId")
                .HasDatabaseName("ix_stamp_transaction_user_id");

            b.ToTable("stamp_transaction", "public");
        });

        modelBuilder.Entity("Loop.Domain.Transactions.PointsTransaction", b =>
        {
            b.Property<Guid>("PointsTxId")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("points_tx_id");

            b.Property<int>("Amount")
                .HasColumnType("integer")
                .HasColumnName("amount");

            b.Property<DateTime>("CreatedAt")
                .ValueGeneratedOnAdd()
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at")
                .HasDefaultValueSql("now()");

            b.Property<Guid?>("RelatedReceiptId")
                .HasColumnType("uuid")
                .HasColumnName("related_receipt_id");

            b.Property<Guid>("ShopId")
                .HasColumnType("uuid")
                .HasColumnName("shop_id");

            b.Property<string>("Type")
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnType("character varying(20)")
                .HasColumnName("type");

            b.Property<Guid>("UserId")
                .HasColumnType("uuid")
                .HasColumnName("user_id");

            b.HasKey("PointsTxId")
                .HasName("pk_points_transaction");

            b.HasIndex("RelatedReceiptId")
                .HasDatabaseName("ix_points_transaction_related_receipt_id");

            b.HasIndex("ShopId")
                .HasDatabaseName("ix_points_transaction_shop_id");

            b.HasIndex("UserId")
                .HasDatabaseName("ix_points_transaction_user_id");

            b.ToTable("points_transaction", "public");
        });

        modelBuilder.Entity("Loop.Domain.Users.User", b =>
        {
            b.Property<Guid>("UserId")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("user_id");

            b.Property<DateTime>("CreatedAt")
                .ValueGeneratedOnAdd()
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at")
                .HasDefaultValueSql("now()");

            b.Property<string>("FirstName")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("character varying(100)")
                .HasColumnName("first_name");

            b.Property<string>("Gender")
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnType("character varying(10)")
                .HasColumnName("gender");

            b.Property<string>("LastName")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("character varying(100)")
                .HasColumnName("last_name");

            b.Property<string>("PasswordHash")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("password_hash");

            b.Property<string>("Phone")
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnType("character varying(20)")
                .HasColumnName("phone");

            b.Property<string>("ProfileImageUrl")
                .HasMaxLength(512)
                .HasColumnType("character varying(512)")
                .HasColumnName("profile_image_url");

            b.Property<Guid>("TierId")
                .HasColumnType("uuid")
                .HasColumnName("tier_id");

            b.HasKey("UserId")
                .HasName("pk_user");

            b.HasIndex("Phone")
                .IsUnique()
                .HasDatabaseName("ix_user_phone");

            b.HasIndex("TierId")
                .HasDatabaseName("ix_user_tier_id");

            b.ToTable("user", "public");

            b.HasData(
                new
                {
                    UserId = new Guid("22222222-2222-2222-2222-222222222222"),
                    CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                    FirstName = "Regular",
                    Gender = "Male",
                    LastName = "User",
                    PasswordHash = "seeded-password-hash",
                    Phone = "+962790000001",
                    ProfileImageUrl = "https://cdn.loop.local/users/default-avatar.png",
                    TierId = new Guid("11111111-1111-1111-1111-111111111111")
                });
        });

        modelBuilder.Entity("Loop.Domain.Users.UserSession", b =>
        {
            b.Property<Guid>("SessionId")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("session_id");

            b.Property<DateTime>("CreatedAt")
                .ValueGeneratedOnAdd()
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at")
                .HasDefaultValueSql("now()");

            b.Property<DateTime>("ExpiresAtUtc")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("expires_at_utc");

            b.Property<string>("RefreshTokenHash")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("character varying(128)")
                .HasColumnName("refresh_token_hash");

            b.Property<Guid>("UserId")
                .HasColumnType("uuid")
                .HasColumnName("user_id");

            b.HasKey("SessionId")
                .HasName("pk_user_session");

            b.HasIndex("RefreshTokenHash")
                .IsUnique()
                .HasDatabaseName("ix_user_session_refresh_token_hash");

            b.HasIndex("UserId")
                .HasDatabaseName("ix_user_session_user_id");

            b.ToTable("user_session", "public");
        });

#pragma warning restore 612, 618
    }
}
